# Generated by Django 3.1.1 on 2021-05-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system', '0004_auto_20210525_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='File_005.jpeg', upload_to=''),
        ),
    ]
